### ISSUE TITLE
Mod+P runs dmenu but doesn't execute any application

### ISSUE THREAD

**Issue by sadid** [vicfryzel/xmonad-config#12]
I've an arch linux installation and current git reposistory has been cloned., and xmonad/xmobar works perfect. But the default dmenu-with-yeganesh doesn't do anything it appears but doesn't launch the app. The following modificaiton solves the problem for my case. I'm not sure if this problem is glabal and effects all users:

in the ~/.xmonad/bin/dmenu-with-yeganesh the execution command should be added i.e.:

this line: dmenu_path | ~/.cabal/bin/yeganesh -- -nb ....
should be modifedi to this:
exec $(dmenu_path | ~/.cabal/bin/yeganesh -- nb .......)

best regards

**Comment by vicfryzel** [comment]
Fixed w/ latest merge. Thanks @vohof
