### ISSUE TITLE
xsession is in /bin folder

### ISSUE THREAD

**Issue by sandric** [vicfryzel/xmonad-config#14]
In readme you giving such a command:

    ln -s ~/.xmonad/xsession ~/.xsession (and correspoding for .xinitrc)
but xsession is in /bin forlder so it should be
 
    ln -s ~/.xmonad/bin/xsession ~/.xsession

no?

**Comment by vicfryzel** [comment]
Hey @sandric. This was fixed in e671c81ae5e458be780e55a4c9ebbb2e8e65855c. Thanks!
