### ISSUE TITLE
Add an open source license?

### ISSUE THREAD

**Issue by seagreen** [vicfryzel/xmonad-config#15]
I love how simple your config is and am basing parts of my own public xmonad.hs (and [bin files](https://github.com/seagreen/vivaine/blob/master/bin/screenshot)) on it.

Any chance you could add an open source license to the project?

**Comment by vicfryzel** [comment]
Hey @seagreen. What do you need me to add a license for?

**Comment by vicfryzel** [comment]
@seagreen please reopen if you have a strong opinion.
