### ISSUE TITLE
Not working "out of the box" on Ubuntu 14.10?

### ISSUE THREAD

**Issue by m3hr** [vicfryzel/xmonad-config#16]
Hi, I was looking for a sane, easy-to-use configuration for xmonad and I followed the directions but when I load xmonad none of the scripts work? dmenu works in a default config of xmonad but stops coming up with mod-P when I have this enabled. I'm not sure what's wrong and I'd like to be able to implement this. 

I'm not asking for personal tech support (well sorta) 'cause that can take time for a busy dev like yourself lol, but I'm curious if there's something I missed from the readme or an installation requirement. Thanks!

**Comment by JDevlieghere** [comment]
What operating system are you using? I'm experiencing some trouble too with dmenu on Fedora 21. Running `dmenu-with-yeganesh` from terminal works flawlessly. Anyway, I'll look into it when I have some more time at hand.

**Comment by m3hr** [comment]
Ubuntu 14.10. It doesn't... really activate activate this config at all. lol

**Comment by aaronwinter** [comment]
Same issue here :-(
