### ISSUE TITLE
Trying to get yeganesh to actually launch something, yet to no avail.

### ISSUE THREAD

**Issue by axg-ux** [vicfryzel/xmonad-config#18]
So I've been trying to use this config as my starter with xmonad, but it's been pretty rough so far, finding out what things are defined specifically for the original creator and then realizing that I have to change them.

Well at this point I have no idea what I'm supposed to do in order to get yeganesh to work. I did not modify the configs mapping to launch and it successfully does so, however it doesn't actually "launch stuff" when I press enter. I ran dmenu_run from the command line, and that worked as expected, so I have no idea what it might be.

**Comment by vicfryzel** [comment]
Hey there,

Trying to figure out exactly what you're experiencing. Is the following true?

- Press Alt + p
- See dmenu at the top of the screen
- Type a command (for instance xterm)
- Press enter
- Don't see xterm

Is that correct?

**Comment by axg-ux** [comment]
Yes that's exactly what's happening. Not sure what could cause this. Have not changed a thing in the config other than getting xmobar to work with my single screen, rebinding mod to super and changing the default terminal. I'm not running any gnome stuff.. don't know if that matters. Seems like you are utilizing some of its userspace.

**Comment by vicfryzel** [comment]
From the command line, what happens when you type `yeganesh -x`?

**Comment by abhiranjankumar00** [comment]
I also have the same issue. 

@vicfryzel: `yeganesh -x` returns the command to be executed, without execution. It appears the our version of yeganesh don't have the capability to execute commands.

Version details:

- yeganesh version 2.5
- dmenu-4.5

**Comment by abhiranjankumar00** [comment]
Played around some of the previous fix related to yeganesh. This pull request should work on all.

**Comment by abhiranjankumar00** [comment]
BTW, thanks very much for your blog post.

**Comment by vicfryzel** [comment]
@abhiranjankumar00 Oh, I misread the docs for yeganesh. I thought it would refresh the path cache. It actually isn't working for me either. My bad. Merging your pull request now.

**Comment by vicfryzel** [comment]
Sorry for the revert. Realized again that the -x should actually remain. Thanks again @abhiranjankumar00

**Comment by abhiranjankumar00** [comment]
Thanks.
