### ISSUE TITLE
xcompmgr not running from ~/.xmonad/bin/xsession

### ISSUE THREAD

**Issue by obimod** [vicfryzel/xmonad-config#20]
Using Slim and the suggested symbolic link [1], xcompmgr doesn't seem to be running on startup. After installing xtransset-df for window opacity settings and setting an opacity level on a particular window I expected the window's opacity to change but nothing happened.

This led me to run the xcompmgr command in a terminal [3] taken from the bin/xsession file which is symbolically linked to ~/.xsession (and b/c I was originally using xinit instead of slim, ~/.xinitrc). The window immediately reduced in opacity.

This is the primary concern for this ticket, whether the xsession script is mostly blown away by the last exec command or not but first and foremost why xcompmgr isn't running.

However, my personal and private goal is for the windows to fade down their opacity when they loose focus. If you can help me with that I would be greatful. I've linked my commits [2] below so that you can see what I'm working with.

[1] ~/.xsession -> /home/obimod/.xmonad/bin/xsession*
[2] https://github.com/obimod/xmonad-config/commits/master
[3] xcompmgr -n -c -C -t-5 -l-5 -r4.2 -o.55 -F  ...(taken from an archlinux wiki page)

**Comment by vicfryzel** [comment]
Can you confirm the location of xcompmgr on your system? Is it within the PATH defined at the top of xsession?

I just checked, with a fresh slim start, and xcompmgr starts for me.

**Comment by obimod** [comment]
The path is /usr/bin/xcompmgr, one which I believe is always in my path via the bash rc files.

**Comment by obimod** [comment]
I've just confirmed, placing /usr/bin inside the path extension at the top of the file without change to the original issue.

**Comment by vicfryzel** [comment]
Can you redirect the output of `xcompmgr -n` to a static file from xsession?

Something like `xcompmgr -n &> ~/xcompmgr.out`

I'm wondering if it's crashing or being killed or something after being started from within xsession.

**Comment by obimod** [comment]
Will do. ModMask+Shift+q should force the execution?

**Comment by vicfryzel** [comment]
Yeah, Mod+Shift+q should exit xmonad, and thus take you back into slim where you can login again and re-run xsession.

**Comment by obimod** [comment]
Well no redirect from xcompmgr having changed the line inside bin/xsession to:
```
# [ ... ]
# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n -c -C -t-5 -l-5 -r4.2 -o.55 -F &> ~/.xcompmgr.out &
```

Looks like I have some work to do regardless:
.xsession-errors -- http://paste.ubuntu.com/12316183/

**Comment by vicfryzel** [comment]
Oops, on my previous command, it should've been `xcompmgr -n >& ~/xcompmgr.out &` which also redirects stderr. However, you're right, .xsession-errors is already capturing stderr.

For what it's worth, the xsession file is meant to be customized to your preferences. However, ck-launch-session should've been installed as part of the guide for Arch. Did you run the install steps for xmonad-config?

**Comment by obimod** [comment]
Yup, I've ran all of the install steps. Had to install ConsoleKit (debian jessie box) which didn't come with the OS. Not quite sure what the deal is, my GPU drivers seem to be complaining:
```
[61489:61489:0908/133008:ERROR:gl_context_glx.cc(54)] Failed to create GL context with glXCreateContextAttribsARB.
[61489:61489:0908/133008:ERROR:gpu_info_collector.cc(41)] gfx::GLContext::CreateGLContext failed
[61489:61489:0908/133008:ERROR:gpu_info_collector.cc(95)] Could not create context for info collection.
[61489:61489:0908/133008:ERROR:gpu_main.cc(422)] gpu::CollectGraphicsInfo failed (fatal).
[61489:61489:0908/133008:ERROR:gpu_child_thread.cc(227)] Exiting GPU process due to errors during initialization
```

Those are the only errors being spit out now.

**Comment by obimod** [comment]
I'm running proprietary nvidia drivers, so god knows what's going on there. Feel free to close as a snowflake configuration problem.

**Comment by vicfryzel** [comment]
Please re-open if you can't get it.
