### ISSUE TITLE
startup looks like it's working for ~5 sec. and then switches to a nautilus desktop-looking view, and I can't open any programs

### ISSUE THREAD

**Issue by freckletonj** [vicfryzel/xmonad-config#21]
I'm on Ubuntu 16.04 using Stack instead of normal cabal, and since I'm new to xmonad, and haskell, I'm not sure if I've botched something up.

In trying to get xmonad to work, I ended up doing `sudo apt-get install xmonad ...` as well as `stack install xmonad`, so I'm not sure which is being used but xmonad finally sort of works. I removed all of my attempts at a custom config before trying this lib, which I think is a great idea btw, and it's super glitchy. 

As soon as I log in to xmonad, it opens 2 bash terminals and a chrome window, but those only exist for like 5 sec. before they all disappear, to be found on none of the alternate workspaces, and the entire screens turns to my nautilus desktop, and icons respond to my mouse, but i can't open any folders, and i can't open any programs including a new terminal. I _can_ logout, and back into my normal Ubuntu (is it Unity?) in order to post this issue.

Any idea what I've done wrong? Or are there any logs somewhere I can send you that might help discern whats up?

**Comment by freckletonj** [comment]
ah, so I linked to .xmonad/bin/.xsession, which I found doesn't exist, (so I needed to delete it), and then I found that this repo's xsession file calls up a `gnome-session` which for some reason glitches out, and I can't find out why. So, commenting out that line allows me to use xmonad, but I'd still like to understand what glitched

**Comment by abhiranjankumar00** [comment]
You can find error logs in `~/.xsession-errors`.

`vim $(which gnome-session)` can help you.

**Comment by vicfryzel** [comment]
@freckletonj hit me up if you're still running into issues.
