### ISSUE TITLE
Add volume indicator to xmobar

### ISSUE THREAD

**Issue by hamtie** [vicfryzel/xmonad-config#22]
This isn't really an issue, but I added some volume indicators to my xmobar, and thought I'd let you know in case you'd like to do the same.

See
https://github.com/hamtie/xmonad-config/commit/6e0bed589bac389a9127797c86786c8fd759b189

Cheers.

**Comment by vicfryzel** [comment]
Hey thanks! If you send me a pull request for just the volume-related bits, I'll accept it.
