### ISSUE TITLE
stalonetray not working

### ISSUE THREAD

**Issue by dandelionmane** [vicfryzel/xmonad-config#26]
I have an empty space where my stalonetray should be. I'm not sure what's wrong, as I haven't used stalone tray before.

* I'm using xmonad 0.13
* I'm on almost-unmodified head ( a few trivial changes like new keyboard shortcuts)
* I adjusted the resolutions in stalonetrayrc-single as directed
* I have stalonetrayrc-single linked to .stalonetrayrc

**Comment by vicfryzel** [comment]
What's the output of the command `stalonetray -c ~/.xmonad/stalonetrayrc-single` ?

**Comment by dandelionmane** [comment]
There's no output. However, it does do something: the empty space where the stalonetray should appear switches from showing the desktop background to being a black rectangle. The rectangle is black even if I change the stalonetray background color to something else, like red.

**Comment by dandelionmane** [comment]
There's another issue in my setup which is that cabal installing xmonad 0.13 broke the path configuration for xmonad, so xmonad doesn't have the correct path or user environment set. I'm not sure if that could be causing this issue.

**Comment by vicfryzel** [comment]
Hey,

Some of this stuff doesn't have to do with the config, but some advice to try:

Add the path to xmonad (and other cabal binaries) to /etc/profile. This will fix your path issue globally for all users. Your distro might have an /etc/profile.d directory, which is just a directory of scripts run at profile instantiation.

If the rectangle where stalonetray should be fills up, it's probably running. Try keeping that command running and then opening an app with a tray icon. Do you see the icon?

-Vic

**Comment by dandelionmane** [comment]
Yep, /etc/profile was the right place to fix my script issues, and stalonetray was working, I just didn't have any apps that wanted to make a tray icon.

Thanks both for taking the time to publish your xmonad config (this is a really great starting point) and for helping me with my issues. :)
